# Generated by Django 5.1.7 on 2025-03-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracs1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
